function trackingData = addTrackingRow( ...
    trackingData,...
    sourceFile,...
    videoName,...
    speakerName,...
    emotionLabel,...
    totalFramesVideo,...
    speakerFramesFound,...
    framesExtracted,...
    unknownCount,...
    errorUTACount,...
    status)

% ========================================================================
% ADDTRACKINGROW
%
% Adds one row to tracking table.
%
% ========================================================================

newRow = table( ...
    string(sourceFile), ...
    string(videoName), ...
    string(speakerName), ...
    string(emotionLabel), ...
    totalFramesVideo, ...
    speakerFramesFound, ...
    framesExtracted, ...
    unknownCount, ...
    errorUTACount, ...
    string(status), ...
    'VariableNames',{ ...
        'SourceFile', ...
        'VideoName', ...
        'ExpectedSpeaker', ...
        'Emotion', ...
        'TotalFramesVideo', ...
        'SpeakerFramesFound', ...
        'FramesExtracted', ...
        'UnknownCount', ...
        'ErrorUTACount', ...
        'Status'});

trackingData = [trackingData; newRow];

end