function pyppboxData = loadPyppboxFile(filename)

pyppboxData = readtable( ...
    filename,...
    'Delimiter','\t',...
    'ReadVariableNames',false);

pyppboxData.Properties.VariableNames = { ...
    'FrameNumber',...
    'NeckPosition',...
    'DeepIDLabel',...
    'FaceIDLabel',...
    'BoundingBoxDimensions',...
    'BoundingBoxCoordinates',...
    'MiniFrameCoordinates'};

pyppboxData.NeckPosition = ...
    convertCoordinateColumn(pyppboxData.NeckPosition);

pyppboxData.BoundingBoxDimensions = ...
    convertCoordinateColumn(pyppboxData.BoundingBoxDimensions);

pyppboxData.BoundingBoxCoordinates = ...
    convertCoordinateColumn(pyppboxData.BoundingBoxCoordinates);

pyppboxData.MiniFrameCoordinates = ...
    convertCoordinateColumn(pyppboxData.MiniFrameCoordinates);

pyppboxData.DeepIDLabel = string(pyppboxData.DeepIDLabel);

pyppboxData.FaceIDLabel = string(pyppboxData.FaceIDLabel);

end